### PR TITLE
fix: prevent rel path for __dirname, __filename

### LINKED ISSUE #93: __dirname and __filename must be absolute at any platform
Hello!
Awesome package! It helped me a lot when switching the project to ESM.

`${/file:\/{2,3}(.+)\/[^/]/.exec(import.meta.url)[1]}` removes leading slash and makes path relative on linux.
I fixed it like `${process.platform === 'win32' ? '' : '/'}${__dirname}`, but it would be nice to make auto replacing

### PR DESCRIPTION
**Pull request by triadium**
Closes #93

### CODE REVIEW

File: src/test/ts/__snapshots__/fix.ts.snap [hunk 1]
```diff
@@ -107,7 +107,7 @@ export const foobaz = foo + 'baz';
 export { foo as foo1 } from './foo.js';
 export const foo2 = await import('./foo');
 export { qux } from './qux.js';
-export const dirname = /file:\\/{2,3}(.+)\\/[^/]/.exec(import.meta.url)[1];
+export const dirname = \`\${process.platform === 'win32' ? '' : '/'}\${/file:\\/{2,3}(.+)\\/[^/]/.exec(import.meta.url)[1]}\`;
```
Comment (antongolub) [inline src/test/ts/__snapshots__/fix.ts.snap:110]: Smth seems wrong here. I'd expect:
```js
export const dirname = `${process.platform === 'win32' ? '' : '/'}${}/file:\\/{2,3}(.+)\\/[^/]/.exec(import.meta.url)[1];`
```

**Review by antongolub — CHANGES_REQUESTED** [review]

File: src/test/ts/__snapshots__/fix.ts.snap (hunk 1 above)
Comment (antongolub) [reply src/test/ts/__snapshots__/fix.ts.snap:110]: It's a snapshot)) My fault.

**Comment by antongolub** [comment]
@dimonka83 , take a look too

**Review by antongolub — COMMENTED** [review]
@triadium,

LGTM! Thanks for the contribution.

**Review by antongolub — APPROVED** [review]
